name:                Bleep
version:             0.1.0.0
github:              "joelffg/Bleep"
license:             BSD3
author:              "Joel Felipe"
maintainer:          "joelfelipe07@gmail.com"
copyright:           "2018 Joel Felipe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joelffg/Bleep#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Bleep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Bleep

tests:
  Bleep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Bleep
